spring.application.name=greedy_gym

# ---- DataSource (MariaDB en 3306) ----
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/greedy_gym?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
spring.datasource.username=diego
spring.datasource.password=greedy

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ---- Mail (mejor usar env vars en prod) ----
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=greedyteam0@gmail.com
spring.mail.password=upiz bhvd orss pqls
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ---- Mercado Pago ----
mercadopago.access-token=APP_USR-1161916719081917-092219-7d27c8faacdc9c984b9bd4539830b21b-2708507674
mercadopago.back-url.success=https://roily-hydraulic-renna.ngrok-free.dev/greedy_gym/api/socio/pagos/success
mercadopago.back-url.pending=https://roily-hydraulic-renna.ngrok-free.dev/greedy_gym/api/socio/pagos/pending
mercadopago.back-url.failure=https://roily-hydraulic-renna.ngrok-free.dev/greedy_gym/api/socio/pagos/failure
