spring.application.name=biblioteca
spring.main.allow-bean-definition-overriding=true

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/biblio_db?useUnicode=true&characterEncoding=utf8&serverTimezone=America/Argentina/Mendoza
spring.datasource.username=root
spring.datasource.password=adminAdmin
# (opcional) driver explícito:
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update

# Forzar dialecto MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Cambiar puerto para evitar conflicto cuando 8080 está ocupado
server.port=8080

# Debug de Spring Security para ver flujo de autenticación en consola
logging.level.org.springframework.security=DEBUG
server.error.include-message=always



# Auth0 Configuration
auth0.domain=dev-cxc35bm4ceatbg7p.us.auth0.com
auth0.audience=https://biblioteca-api

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.auth0.client-id=WXANt7liImoKcJJWBH0iiwy41EvUfHJu
spring.security.oauth2.client.registration.auth0.client-secret=iscjGHlAIDgmA4nIAnetcwWylGtt7yW0Nc5n0gfg9R6swo6bwrPdWMagD7FJVTqT
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# OAuth2 Provider Configuration
spring.security.oauth2.client.provider.auth0.issuer-uri=https://${auth0.domain}/

# JWT Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${auth0.domain}/

