spring.application.name=greedy_cars
spring.main.allow-bean-definition-overriding=true

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3307/greedy_cars_db?useUnicode=true&characterEncoding=utf8&serverTimezone=America/Argentina/Mendoza
spring.datasource.username=greedy_cars
spring.datasource.password=adminAdmin
# (opcional) driver explícito:
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.ddl-auto=update

# Forzar dialecto MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=9000

# Debug de Spring Security para ver flujo de autenticación en consola
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
