spring.application.name=greedy_cars
spring.main.allow-bean-definition-overriding=true

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3307/greedy_cars_db?useUnicode=true&characterEncoding=utf8&serverTimezone=America/Argentina/Mendoza
spring.datasource.username=greedy_cars
spring.datasource.password=adminAdmin
# (opcional) driver explícito:
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.ddl-auto=update

# Forzar dialecto MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=9000

# Debug de Spring Security para ver flujo de autenticación en consola
logging.level.org.springframework.security=DEBUG
server.error.include-message=always

app.jwt.secret=replace_this_with_a_long_random_secret_at_least_256_bits_base64_or_random_string
# 1 hora, por ejemplo
app.jwt.expiration-ms=3600000

# Configuración Mercado Pago
mercadopago.access-token=APP_USR-1161916719081917-092219-7d27c8faacdc9c984b9bd4539830b21b-2708507674
mercadopago.back-url-success=http://NGROK_URL/greedy_cars/api/pagos/mp/success #no configurado todavía
mercadopago.back-url-failure=http://NGROK_URL/greedy_cars/api/pagos/mp/failure
mercadopago.back-url-pending=http://NGROK_URL/greedy_cars/api/pagos/mp/pending
